name: jaffle_shop

profile: jaffle_shop

seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +transient: false
  jaffle_shop:
    profit_us:
      +schema: TRAINING
      +materialized: table
    profit_uk:
      +schema: TRAINING
      +materialized: table
    profit_india:
      +schema: TRAINING
      +materialized: table
    customers_stg:
      +schema: L2_PROCESSING
    orders_stg:
      +schema: L2_PROCESSING
    orderitems_stg:
      +schema: L2_PROCESSING
    customerrevenue:
      +materialized: table
    orders_fact:
      +schema: L2_PROCESSING
      +materialized: table